version: "3.7"
services:
  api-app:
           container_name:  api-app
           image: image/api-app  
           restart: always
           build: .
           ports:
             - "7500:7500"
           networks:
            - webappnetwork
networks:
    webappnetwork:
        driver: bridge